# Generated by Django 5.1 on 2024-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_multiple_choice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='SingleMCQ',
        ),
        migrations.RemoveField(
            model_name='readingmultiplechoice',
            name='totalScore',
        ),
        migrations.AddField(
            model_name='readingmultiplechoice',
            name='ansScript',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='readingmultiplechoice',
            name='correctAns',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='readingmultiplechoice',
            name='options',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='readingmultiplechoice',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='readingmultiplechoice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
