# Generated by Django 5.1 on 2024-08-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_paragraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='paragraphNo',
        ),
        migrations.AddField(
            model_name='reorderingparagraph',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
