# Generated by Django 5.1 on 2024-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_paragraph', '0002_remove_paragraph_paragraphno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.AddField(
            model_name='reorderingparagraph',
            name='ansScript',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reorderingparagraph',
            name='correctAns',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reorderingparagraph',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
